FROM freqtradeorg/freqtrade:stable

# Installiamo le librerie pesanti per l'Intelligenza Artificiale e la matematica vettoriale
RUN pip install --user torch pandas-ta joblib scikit-learn

RUN pip install --user --no-cache-dir plotly
